const mockPosts = [
  {
    id: 1,
    name: "John Doe",
    username: "@jdoe",
    residence: "1201A",
    date: "19/02/2012 - 16:45",
    likes: [1],
    comments: [],
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sagittis molestie lacus vel consequat.",
  },
  {
    id: 2,
    name: "Shereen Kavanagh",
    username: "@shereen",
    residence: "201B",
    date: "19/02/2012 - 16:45",
    likes: [1, 1, 1],
    comments: [1, 1],
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sagittis molestie lacus vel consequat.",
  },
  {
    id: 3,
    name: "Louise Burns",
    username: "@louise",
    residence: "101A",
    date: "19/02/2012 - 14:45",
    likes: [1, 1],
    comments: [],
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sagittis molestie lacus vel consequat.",
  },
  {
    id: 4,
    name: "Siana Gilliam",
    username: "@siana",
    residence: "1502B",
    date: "19/02/2012 - 13:45",
    likes: [1, 1, 1, 1, 1, 1, 1, 1, 1],
    comments: [1, 1, 1, 1],
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sagittis molestie lacus vel consequat.",
  },
  {
    id: 6,
    name: "Mikaeel Ellis",
    username: "@mikaeel",
    residence: "1103C",
    date: "19/02/2012 - 11:45",
    likes: [1, 1, 1],
    comments: [1],
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sagittis molestie lacus vel consequat.",
  },
  {
    id: 7,
    name: "Zaine Webber",
    username: "@zaine",
    residence: "201D",
    date: "19/02/2012 - 11:15",
    likes: [],
    comments: [1, 1],
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sagittis molestie lacus vel consequat.",
  },
  {
    id: 8,
    name: "Kieran Carson",
    username: "@kieran",
    residence: "301A",
    date: "19/02/2012 - 11:03",
    likes: [1, 1, 1],
    comments: [1],
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sagittis molestie lacus vel consequat.",
  },
  {
    id: 9,
    name: "Simra Wiley",
    username: "@simra",
    residence: "120B",
    date: "19/02/2012 - 09:45",
    likes: [1],
    comments: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sagittis molestie lacus vel consequat.",
  },
];

export default mockPosts;
